###
### A complete description of a Prefect Deployment for flow 'etl-parent-flow'
###
name: Total Energy ETL
description: null
version: 10c36a8c8034dcb812490bf09fb79c17
# The work queue that will handle this deployment's runs
work_queue_name: default
tags: []
parameters: {
  "years": [1980,
            1981,
            1982,
            1983,
            1984,
            1985,
            1986,
            1987,
            1988,
            1989,
            1990,
            1991,
            1992,
            1993,
            1994,
            1995,
            1996,
            1997,
            1998,
            1999,
            2000,
            2001,
            2002,
            2003,
            2004,
            2005,
            2006,
            2007,
            2008,
            2009,
            2010,
            2011,
            2012,
            2013,
            2014,
            2015,
            2016,
            2017,
            2018,
            2019,
            2020,
            2021,
            2022,
            2023]
}
schedule: null
infra_overrides: {}
infrastructure:
  type: process
  env: {}
  labels: {}
  name: null
  command: null
  stream_output: true
  working_dir: null
  block_type_slug: process
  _block_type_slug: process

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: etl-parent-flow
manifest_path: null
storage: null
path: /home/tim/Documents/Projects/Oil/prefect
entrypoint: ingest_totalenergy.py:etl_parent_flow
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    years:
      title: years
      default:
      - 2020
      - 2021
      - 2022
      - 2023
      position: 0
      type: array
      items:
        type: integer
  required: null
  definitions: null
